// Generated by scripts/generate-console-models.ts; offline suggestions, not account entitlements.
export const CONSOLE_MODEL_CATALOG = {
  "sdkVersion": "1.25.1",
  "providers": {
    "openai": {
      "revision": "2026-09-12",
      "sourceSha256": "af33783afbf76d7fd12776a2a19244663c286a0f7bc6f05549e2ffe8a3e41900",
      "models": [
        "gpt-6-astra",
        "gpt-5.6-sol",
        "gpt-5.6-terra",
        "gpt-5.6-luna",
        "gpt-5.5",
        "gpt-5.4",
        "gpt-5.4-mini",
        "gpt-4o-mini"
      ]
    },
    "qwen": {
      "revision": "2026-09-20",
      "sourceSha256": "f52a311095ad69f94bdfdbb71f7011ec7e19d24a5c7d7a116f53d7d13c8c6008",
      "models": [
        "qwen3.8-omni-flash",
        "qwen3.8-max-0902",
        "qwen3.8-max",
        "qwen3.8-flash",
        "qwen3.8-max-preview",
        "qwen3.7-max",
        "qwen3.7-plus",
        "qwen3.6-flash",
        "qwen3.5-omni-plus",
        "qwen-plus"
      ]
    },
    "gemini": {
      "revision": "2026-09-16",
      "sourceSha256": "ef26943ffd54a786e06f232adf06585ccfdddb6450dd090b2e7bc01d668153b4",
      "models": [
        "gemini-3.8-flash",
        "gemini-3.7-flash",
        "gemini-3.6-flash",
        "gemini-3.5-flash-lite",
        "gemini-3.5-flash",
        "gemini-3.1-pro-preview",
        "gemini-3.1-pro-preview-customtools",
        "gemini-3-flash-preview",
        "gemini-3.1-flash-lite"
      ]
    },
    "meta": {
      "revision": "2026-09-04",
      "sourceSha256": "0e655bb5cee4dd5430336bec10d1a9cfb08a4fdc5902c211d91599f6f92492f6",
      "models": [
        "muse-spark-1.3",
        "muse-spark-1.2",
        "muse-spark-1.2-contributor",
        "muse-spark-1.1"
      ]
    }
  }
} as const;
