import {fillRendererFixture} from "../src/renderer-fixture-data.js";
import {app,BrowserWindow,ipcMain} from "electron";
import {mkdir,writeFile,readFile} from "node:fs/promises";
import {execFileSync} from "node:child_process";
import {createHash,randomUUID} from "node:crypto";
import path from "node:path";
import assert from "node:assert/strict";
import {launchProjectRuntime,type ProjectRuntime} from "../src/runtime-host.js";
import {desktopProviders} from "../src/model-selection.js";
const [build,helper,report]=process.argv.slice(2) as [string,string,string];
app.setPath("userData",path.join(report,"profile"));
let host:ProjectRuntime|undefined, phase="startup";
const evidence:Record<string,unknown>={provider:"qwen",model:"qwen3.8-max",live:true,packagedRuntime:true,packagedRenderer:true,credentialSource:"local-env-private-helper",nativeKeychain:false,mainProcess:"live-test-driver"};
void app.whenReady().then(async()=>{
 const workspace=path.join(report,"repo");await mkdir(workspace);execFileSync("git",["init","-q",workspace]);
 const marker=`QWEN_${randomUUID().replaceAll("-","")}`;
 await writeFile(path.join(workspace,"check.txt"),marker+"\n");
 const project={key:"qwen-live-project",name:"Qwen live check",workspace,lastOpenedAt:Date.now(),modelSelection:{provider:"qwen",model:"qwen3.8-max"}};
 const start=()=>launchProjectRuntime(project,{buildDirectory:build,credentialHelper:helper,directory:path.join(report,"socket"),stateDirectory:path.join(report,"state"),fixture:false,recover:true});
 host=await start();assert.equal(host.context.credentialConfigured,true);
 const window=new BrowserWindow({width:1120,height:760,show:false,webPreferences:{preload:path.join(build,"preload.cjs"),sandbox:true,contextIsolation:true,nodeIntegration:false}});
 ipcMain.handle("harness:providers",()=>desktopProviders());ipcMain.handle("harness:initial-project",()=>host!.context);ipcMain.handle("harness:projects",()=>[project]);ipcMain.handle("harness:tasks",()=>[]);
 ipcMain.handle("harness:command",(_e,p)=>host!.command(p.command));ipcMain.handle("harness:events",(_e,p)=>host!.events({sessionId:p.sessionId,after:p.after}));
 ipcMain.handle("harness:review",(_e,p)=>host!.review(p.sessionId,p.runId));ipcMain.handle("harness:resolve-review",(_e,p)=>host!.resolveReview(p.ticketId,p.approve));
 ipcMain.handle("harness:update-status",()=>({status:"unconfigured"}));
 await window.loadFile(path.join(build,"index.html"));
 const js=(s:string)=>window.webContents.executeJavaScript(s);
 const wait=async(s:string,ms=150000)=>{const until=Date.now()+ms;while(Date.now()<until){if(await js(s))return;await new Promise(r=>setTimeout(r,100));}throw new Error("LIVE_TIMEOUT");};
 const click=(s:string)=>js(`document.querySelector(${JSON.stringify(s)}).click()`);
 const send=async(prompt:string)=>{
  await fillRendererFixture(window, "#prompt", prompt);
  await wait("document.querySelector('[data-action=start]')?.disabled===false",10000);await click('[data-action=start]');
 };
 await wait("document.querySelector('[data-action=new-session]')?.disabled===false",15000);
 assert.equal(await js("document.querySelector('[data-action=select-provider]').value"),"qwen");
 await click('[data-action=new-session]');await wait("Boolean(document.querySelector('main').dataset.sessionId)",10000);
 const sessionId=await js("document.querySelector('main').dataset.sessionId");
 const session=async()=>{const r=await host!.command({method:"session.get",sessionId});assert(r.ok&&r.data.kind==="session");return r.data.session;};
 const finished=async(previous:number,status:string)=>{
  const until=Date.now()+150000;
  while(Date.now()<until){const s=await session();if(s.runs.length>previous){const last=s.runs.at(-1)!;if(last.status===status)return last;if(["failed","cancelled","timed_out"].includes(last.status))throw new Error("LIVE_RUN_FAILED");}await new Promise(r=>setTimeout(r,250));}throw new Error("LIVE_TIMEOUT");
 };
 phase="read-and-stream";
 await send("Use read_file to read check.txt in this repository. Reply with its exact contents and nothing else. Do not modify any files or call other tools.");
 await finished(0,"completed");await wait(`document.querySelector('.timeline')?.innerText.includes(${JSON.stringify(marker)})`);
 const page=await host.events({sessionId,after:0});const serialized=JSON.stringify(page);
 assert(page.events.some(e=>e.activity.type==="tool-result"&&e.activity.toolName==="read_file"&&e.activity.isError!==true));assert(page.events.some(e=>e.activity.type==="text-delta"));assert(serialized.includes(marker));
 evidence.readTool=true;evidence.rendererResponse=true;evidence.providerModelBinding=(await session()).runs.every(r=>r.provider==="qwen"&&r.model==="qwen3.8-max");
 phase="conversation-continuation";
 await send("Without calling any tools, repeat the exact marker you read in the previous turn, followed by a space and CONTINUED.");
 await finished(1,"completed");await wait(`document.querySelector('.timeline')?.innerText.includes(${JSON.stringify(marker+" CONTINUED")})`);evidence.continuation=true;
 phase="approval-request";
 const digest="sha256:"+createHash("sha256").update(marker+"\n").digest("hex");
 await send(`Call apply_reviewed_replacement exactly once with this JSON: ${JSON.stringify({path:"check.txt",expectedDigest:digest,oldText:marker,newText:marker+"_EDITED"})}. This tool requests operator approval; do not ask in text. Call no other tools. After the approved result reply exactly QWEN_EDIT_OK.`);
 const pending=await finished(2,"waiting_approval");assert.equal(await readFile(path.join(workspace,"check.txt"),"utf8"),marker+"\n");evidence.approvalBeforeWrite=true;
 phase="restart-and-approve";
 const firstPid=host.context.runtimePid;await host.close();host=await start();assert.notEqual(host.context.runtimePid,firstPid);
 const reloaded=new Promise<void>(resolve=>window.webContents.once("did-finish-load",()=>resolve()));window.webContents.reload();await reloaded;
 await wait("document.querySelector('[data-session]')?.disabled===false",15000);await click(`[data-session="${sessionId}"]`);
 await wait("Boolean(document.querySelector('[data-action=review]'))",10000);await click('[data-action=review]');
 await wait("Boolean(document.querySelector('[data-review-item]'))",10000);
 const review=await host.review(sessionId,pending.runId);assert(review.canApprove);assert(review.items.every(i=>i.name==="apply_reviewed_replacement"));
 // Approval is limited to the exact synthetic edit that this live test requested.
 const resumed=await host.resolveReview(review.ticketId,true);assert(resumed.ok&&resumed.data.kind==="run"&&resumed.data.run.status==="completed");
 assert.equal(await readFile(path.join(workspace,"check.txt"),"utf8"),marker+"_EDITED\n");
 await wait("document.querySelector('.timeline')?.innerText.includes('QWEN_EDIT_OK')",10000);
 evidence.restartRecovery=true;evidence.reviewRenderer=true;evidence.approvedEdit=true;evidence.turns=(await session()).runs.length;
 await writeFile(path.join(report,"chat.png"),(await window.webContents.capturePage()).toPNG());
 phase="complete";await host.close();host=undefined;
 await writeFile(path.join(report,"report.json"),JSON.stringify({...evidence,status:"passed"},null,2));app.exit(0);
}).catch(async()=>{await host?.controlClose("cancel").catch(()=>{});await host?.close().catch(()=>{});await writeFile(path.join(report,"report.json"),JSON.stringify({...evidence,status:"failed",phase},null,2)).catch(()=>{});app.exit(1);});
