import {mkdtemp,mkdir,cp,readFile,writeFile,rm} from "node:fs/promises";
import {createHash} from "node:crypto";
import {execFileSync} from "node:child_process";
import path from "node:path";
const root=path.resolve(import.meta.dir,"..");const directory=await mkdtemp("/tmp/har-installed-");const mount=path.join(directory,"volume"),applications=path.join(directory,"Applications");await mkdir(mount);await mkdir(applications);
const output=path.join(root,"out/installer"),manifest=JSON.parse(await readFile(path.join(output,"release-manifest.json"),"utf8"));
if(path.basename(manifest.artifact.file)!==manifest.artifact.file)throw new Error("INVALID_INSTALLER_NAME");const image=path.join(output,manifest.artifact.file);const hash=async(file:string)=>createHash("sha256").update(await readFile(file)).digest("hex");if(await hash(image)!==manifest.artifact.sha256)throw new Error("INSTALLER_DIGEST_CHANGED");let mounted=false;
const command=(binary:string,args:string[])=>execFileSync(binary,args,{encoding:"utf8",stdio:["ignore","pipe","pipe"]});
try{command("/usr/bin/hdiutil",["attach","-readonly","-nobrowse","-mountpoint",mount,image]);mounted=true;const installed=path.join(applications,"Zhivex Harness.app");await cp(path.join(mount,"Zhivex Harness.app"),installed,{recursive:true,verbatimSymlinks:true,preserveTimestamps:true});const resources=path.join(installed,"Contents/Resources");if(await hash(path.join(resources,"app.asar"))!==manifest.contents.asar.sha256||await hash(path.join(resources,"credential-store"))!==manifest.contents.credentialHelper.sha256)throw new Error("INSTALLED_BYTES_CHANGED");
 command("/usr/bin/hdiutil",["detach",mount]);mounted=false;
 const child=Bun.spawn([process.execPath,"run",path.join(root,"scripts/smoke.ts"),"--packaged","--empty-start","--app-path",installed],{cwd:root,stdout:"pipe",stderr:"pipe"});const [stdout,stderr,exit]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);if(exit!==0)throw new Error(`INSTALLED_SMOKE_FAILED: ${stderr.slice(-12000)}`);const smoke=JSON.parse(stdout.trim().split("\n").at(-1)!);if(!smoke.packaged||!smoke.sqliteBytes||!smoke.separateProcess||!smoke.emptyStartup)throw new Error("INSTALLED_SMOKE_INCOMPLETE");
 const native=JSON.parse(command(path.join(resources,"credential-store"),["self-test"]));if(native.status!=="self-test-passed")throw new Error("INSTALLED_HELPER_FAILED");
 const evidence={schemaVersion:1,artifact:manifest.artifact,temporaryCleanInstall:true,sourceImageDetachedBeforeLaunch:true,installedBytesVerified:true,installedNativeHelper:true,signed:false,notarized:false,gatekeeperDistributionVerified:false,smoke};await writeFile(path.join(output,"installation-check.json"),JSON.stringify(evidence,null,2)+"\n");console.log(JSON.stringify({report:path.join(output,"installation-check.json"),evidence}));
}finally{if(mounted)command("/usr/bin/hdiutil",["detach",mount]);await rm(directory,{recursive:true,force:true});}
