import { test, expect } from "bun:test";
import { execFileSync } from "node:child_process";
import { mkdtemp, mkdir, writeFile, readFile, chmod, rm, access } from "node:fs/promises";
import { openGitHubGitTransport } from "../src/github-git-transport.js";
const git = (repo: string, args: string[]) => execFileSync("/usr/bin/git", ["-C", repo, ...args], { encoding: "utf8" }).trim();
test("network commands isolate repository configuration and use one non-forced refspec", async () => {
    const root = await mkdtemp("/tmp/har-transport-"), repo = root + "/repo", bin = root + "/bin", trace = root + "/trace", config = root + "/network-config"; await mkdir(repo); await mkdir(bin); const originalPath = process.env.PATH;
    let transport: Awaited<ReturnType<typeof openGitHubGitTransport>> | undefined;
    try {
        git(repo, ["init", "-q", "-b", "main"]); git(repo, ["config", "user.name", "Fixture"]); git(repo, ["config", "user.email", "fixture@example.invalid"]); await writeFile(repo + "/a.txt", "fixture\n"); git(repo, ["add", "a.txt"]); git(repo, ["commit", "-qm", "base"]); const base = git(repo, ["rev-parse", "HEAD"]); await writeFile(repo + "/a.txt", "reviewed content\n"); git(repo, ["add", "a.txt"]); git(repo, ["commit", "-qm", "reviewed change"]); const head = git(repo, ["rev-parse", "HEAD"]);
        git(repo, ["remote", "add", "origin", "https://github.com/fixture/repository.git"]); git(repo, ["config", "http.https://github.com/.extraHeader", "REPOSITORY_HEADER_MUST_NOT_REACH_NETWORK"]); git(repo, ["config", "credential.helper", "REPOSITORY_HELPER_MUST_NOT_RUN"]); git(repo, ["config", "remote.origin.mirror", "true"]);
        await writeFile(bin + "/git", `#!/bin/sh\nfor item in "$@"; do\n if [ "$item" = ls-remote ] || [ "$item" = push ]; then\n  printf '%s\\n' "$@" >> '${trace}'\n  /usr/bin/git -C "$2" config --local --list >> '${config}'\n  if [ "$item" = ls-remote ]; then case "$*" in *refs/heads/main) printf '${base}\\trefs/heads/main\\n';; *refs/heads/feat/published) printf '${head}\\trefs/heads/feat/published\\n';; esac; fi\n  exit 0\n fi\ndone\nexec /usr/bin/git "$@"\n`); await chmod(bin + "/git", 0o755); process.env.PATH = bin + ":" + originalPath;
        transport = await openGitHubGitTransport(repo); const destination = { remote: "origin", url: "https://github.com/fixture/repository.git", ref: "refs/heads/main", baseRef: "refs/heads/main" }; expect(await transport.readHead(destination)).toBe(base); const snapshot = await transport.inspect({ ...destination, ref: "refs/heads/feat/reviewed" }); expect(snapshot.head).toBe(head); expect(snapshot.remoteHead).toBeNull(); expect(snapshot.fastForward).toBe(true); expect(snapshot.commits[0]!.files[0]!.after).toBe("reviewed content\n"); const published = await transport.inspectPullRequest({ ...destination, ref: "refs/heads/feat/published" }); expect(published.remoteHead).toBe(head); expect(published.commits).toHaveLength(1); await transport.push(head, destination);
        const argumentsText = await readFile(trace, "utf8"), networkConfig = await readFile(config, "utf8"); expect(networkConfig).not.toContain("REPOSITORY_"); expect(networkConfig).not.toContain("mirror"); expect(argumentsText).toContain(`${head}:refs/heads/main`); expect(argumentsText).toContain("credential.helper=!gh auth git-credential"); expect(argumentsText).not.toContain("--force"); expect(argumentsText).not.toContain("--mirror"); expect(argumentsText).not.toContain(repo);
        git(repo, ["remote", "set-url", "origin", "https://github.com/other/repository.git"]); await expect(transport.push(head, destination)).rejects.toThrow("REMOTE_DESTINATION_CHANGED"); expect(await readFile(trace, "utf8")).toBe(argumentsText);
        const transportRoot = argumentsText.split("\n")[1]!; await transport.close(); transport = undefined; await expect(access(transportRoot)).rejects.toThrow();
    } finally { process.env.PATH = originalPath; if (transport) await transport.close(); await rm(root, { recursive: true, force: true }); }
});
