import "./credential-settings.css";
import {useRef,useState} from "react";
import type {DesktopProvider} from "./bridge.js";
import type {CredentialProbe} from "./credential-store.js";
const messages:Record<CredentialProbe,string>={present:"Clave guardada en el llavero.",missing:"No hay una clave guardada.",saved:"Clave guardada. El proyecto ya usa la nueva credencial.",deleted:"Clave eliminada del llavero.",cancelled:"Configuración cancelada; se conserva la clave anterior.",locked:"Desbloqueá el llavero en Acceso a Llaveros y reintentá.",unavailable:"No se confirmó el acceso al llavero. Consultá el estado antes de reintentar.",invalid:"La clave no es válida: usá un valor sin espacios ni saltos de línea.",unsupported:"El almacén seguro solo está disponible en macOS.",connected:"Conexión autorizada para consultar modelos; no se ejecutó una generación.","invalid-credential":"El proveedor rechazó la clave. Configurá una nueva.",forbidden:"La clave no tiene permiso para consultar modelos.","rate-limited":"El proveedor limitó la consulta. Reintentá más tarde.","network-error":"No se pudo verificar la conexión. Revisá la red y reintentá."};
export function CredentialSettings({providers,initialProvider="openai",changed}:{providers:DesktopProvider[];initialProvider?:string;changed:()=>Promise<void>}){const [provider,setProvider]=useState(initialProvider);const [busy,setBusy]=useState(false),[message,setMessage]=useState("");const lock=useRef(false);
 const act=async(operation:()=>Promise<CredentialProbe>)=>{if(lock.current)return;lock.current=true;setBusy(true);try{const result=await operation();if(["saved","deleted","unavailable"].includes(result))await changed();setMessage(messages[result]);}catch{setMessage("Hay trabajo activo o no se confirmó su cierre. Esperá a que termine antes de cambiar credenciales; si el error persiste, reiniciá la aplicación.");}finally{lock.current=false;setBusy(false);}};
 return <details className="credential-settings"><summary>Credenciales</summary><label>Proveedor<select aria-label="Proveedor de credenciales" value={provider} disabled={busy} onChange={e=>{setProvider(e.target.value);setMessage("");}}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p>La clave se introduce en una ventana segura de macOS y se guarda en el llavero. Cerrá las tareas activas antes de reemplazarla o eliminarla.</p><button disabled={busy} data-action="credential-status" onClick={()=>void act(()=>window.harness.credentialStatus(provider))}>Consultar presencia</button><button disabled={busy} data-action="credential-configure" onClick={()=>void act(()=>window.harness.configureCredential(provider))}>Guardar o reemplazar clave</button><button disabled={busy} data-action="credential-probe" onClick={()=>void act(()=>window.harness.probeCredential(provider))}>Probar conexión</button><button disabled={busy} data-action="credential-delete" onClick={()=>void act(()=>window.harness.deleteCredential(provider))}>Eliminar clave del llavero</button>{message?<p role="status">{message}</p>:null}</details>;
}
