import {PullRequestPanel} from "./PullRequestPanel.js";
import {PushPanel} from "./PushPanel.js";
import {useRef,useState} from "react";
import type {CommitReview,DeliveryChanges} from "./git-delivery.js";
export function GitPanel({projectKey,disabled}:{projectKey:string;disabled:boolean}){
 const pendingKey=`harness.git.pending:${projectKey}`;
 const [changes,setChanges]=useState<DeliveryChanges>(),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(""),[review,setReview]=useState<CommitReview>(),[pending,setPending]=useState<string|undefined>(()=>localStorage.getItem(pendingKey)??undefined),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState("");const guard=useRef(false);
 const refresh=async()=>{setChanges(await window.harness.gitChanges(projectKey));setSelected([]);setReview(undefined);};
 const act=async(fn:()=>Promise<void>)=>{if(guard.current)return;guard.current=true;setBusy(true);setError("");try{await fn();}catch(error){const code=String(error);setError(code.includes("GIT_RUNTIME_BUSY")?"Hay trabajo activo. Esperá o cancelalo antes de preparar archivos o crear el commit.":code.includes("SECRET")||code.includes("PATH_BLOCKED")?"La selección contiene contenido sensible o un archivo protegido. Revisala fuera de esta vista.":code.includes("IDENTITY_REQUIRED")?"Configurá tu nombre y correo en Git antes de revisar el commit.":"No se completó la operación. Actualizá el estado y revisá los archivos; si hay un commit pendiente, consultá su resultado antes de volver a enviarlo.");}finally{guard.current=false;setBusy(false);}};
 return <details className="task-panel git-panel"><summary>Entrega Git</summary><p>Prepará archivos completos y revisá el contenido staged antes de autorizar un commit local sin firma.</p>
 <button type="button" data-action="git-refresh" disabled={busy||disabled} onClick={()=>void act(refresh)}>Actualizar archivos</button>
 {changes?<><p>{changes.blocked?`${changes.blocked} archivos protegidos omitidos.`:""}</p>{changes.files.map(file=><label key={file.path}><input type="checkbox" data-git-path={file.path} checked={selected.includes(file.path)} disabled={busy||disabled||Boolean(pending)} onChange={event=>{setReview(undefined);setSelected(current=>event.target.checked?[...current,file.path]:current.filter(value=>value!==file.path));}}/>{file.path} · {file.staged?"Staged: seleccionar para revisar":"Sin preparar: seleccionar para preparar"}{file.staged&&file.worktree?" · También tiene cambios sin preparar":""}</label>)}
 <button type="button" data-action="git-stage" disabled={busy||disabled||Boolean(pending)||!selected.length||selected.some(name=>changes.files.find(file=>file.path===name)?.staged)} onClick={()=>void act(async()=>{await window.harness.gitStage(projectKey,selected);await refresh();})}>Preparar seleccionados</button>
 <label>Mensaje del commit<textarea data-field="commit-message" value={message} disabled={busy||disabled||Boolean(pending)} onChange={event=>{setMessage(event.target.value);setReview(undefined);}} maxLength={4000}/></label>
 <button type="button" data-action="git-review" disabled={busy||disabled||Boolean(pending)||!message.trim()||!selected.length} onClick={()=>void act(async()=>setReview(await window.harness.gitReviewCommit(projectKey,{paths:selected,message})))}>Revisar commit</button></>:null}
 {review?<div role="region" aria-label="Revisión del commit"><h3>Commit local sin firma</h3><p>Rama: {review.branch}<br/>Destino: repositorio local<br/>Base: {review.head}<br/>Autor: {review.author}<br/>Committer: {review.committer}</p><pre>{review.message}</pre>{review.files.map(file=><details key={file.path}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><h4>Antes</h4><pre>{file.before}</pre><h4>Staged</h4><pre>{file.after}</pre></details>)}<button type="button" data-action="git-commit" disabled={busy||disabled||Boolean(pending)} onClick={()=>void act(async()=>{const id=review.ticketId;localStorage.setItem(pendingKey,id);setPending(id);setReview(undefined);const operation=await window.harness.gitCommit(projectKey,id);localStorage.removeItem(pendingKey);setPending(undefined);setResult(`Commit creado: ${operation.commit}`);await refresh();})}>Autorizar commit local</button><button type="button" onClick={()=>setReview(undefined)}>Volver</button></div>:null}
 {pending?<div role="status"><p>Operación pendiente de confirmar: {pending}</p><button type="button" data-action="git-reconcile" disabled={busy||disabled} onClick={()=>void act(async()=>{const operation=await window.harness.gitReconcile(projectKey,pending);setResult(operation.status==="not-accepted"?"No se aceptó el commit. Podés preparar una revisión nueva.":`Commit confirmado: ${operation.commit}`);localStorage.removeItem(pendingKey);setPending(undefined);await refresh();})}>Consultar resultado</button></div>:null}
 <PushPanel projectKey={projectKey} disabled={disabled||busy||Boolean(pending)}/><PullRequestPanel projectKey={projectKey} disabled={disabled||busy||Boolean(pending)}/>{result?<p role="status">{result}</p>:null}{error?<p role="alert">{error}</p>:null}</details>;
}
