import { FileDiff } from "./FileDiff.js";
import {PullRequestPanel} from "./PullRequestPanel.js";
import { PushPanel } from "./PushPanel.js";
import { useRef, useState } from "react";
import type { CommitReview, DeliveryChanges } from "./git-delivery.js";
export function GitPanel({ projectKey, disabled }: { projectKey: string; disabled: boolean }) {
    const pendingKey = `harness.git.pending:${projectKey}`;
    const [changes, setChanges] = useState<DeliveryChanges>(), [selected, setSelected] = useState<string[]>([]), [message, setMessage] = useState(""), [review, setReview] = useState<CommitReview>(), [pending, setPending] = useState<string | undefined>(() => localStorage.getItem(pendingKey) ?? undefined), [busy, setBusy] = useState(false), [error, setError] = useState(""), [result, setResult] = useState(""); const guard = useRef(false);
    const refresh = async () => { setChanges(await window.harness.gitChanges(projectKey)); setSelected([]); setReview(undefined); };
    const act = async (fn: () => Promise<void>) => { if (guard.current) return; guard.current = true; setBusy(true); setError(""); try { await fn(); } catch (error) { const code = String(error); setError(code.includes("GIT_RUNTIME_BUSY") ? "Work is active. Wait or cancel it before staging files or creating the commit." : code.includes("SECRET") || code.includes("PATH_BLOCKED") ? "The selection contains sensitive content or a protected file. Review it outside this view." : code.includes("IDENTITY_REQUIRED") ? "Configure your name and email in Git before reviewing the commit." : "The operation did not complete. Refresh the status and review the files; if a commit is pending, check its result before submitting it again."); } finally { guard.current = false; setBusy(false); } };
    return <details className="task-panel git-panel"><summary>Git delivery</summary><p>Stage complete files and review the staged content before authorizing an unsigned local commit.</p>
        <button type="button" data-action="git-refresh" disabled={busy || disabled} onClick={() => void act(refresh)}>Refresh files</button>
        {changes ? <><p>{changes.blocked ? `${changes.blocked} protected files omitted.` : ""}</p>{changes.files.map(file => <label key={file.path}><input type="checkbox" data-git-path={file.path} checked={selected.includes(file.path)} disabled={busy || disabled || Boolean(pending)} onChange={event => { setReview(undefined); setSelected(current => event.target.checked ? [...current, file.path] : current.filter(value => value !== file.path)); }} />{file.path} · {file.staged ? "Staged: select to review" : "Unstaged: select to stage"}{file.staged && file.worktree ? " · Also has unstaged changes" : ""}</label>)}
            <button type="button" data-action="git-stage" disabled={busy || disabled || Boolean(pending) || !selected.length || selected.some(name => changes.files.find(file => file.path === name)?.staged)} onClick={() => void act(async () => { await window.harness.gitStage(projectKey, selected); await refresh(); })}>Stage selected files</button>
            <label>Commit message<textarea data-field="commit-message" value={message} disabled={busy || disabled || Boolean(pending)} onChange={event => { setMessage(event.target.value); setReview(undefined); }} maxLength={4000} /></label>
            <button type="button" data-action="git-review" disabled={busy || disabled || Boolean(pending) || !message.trim() || !selected.length} onClick={() => void act(async () => setReview(await window.harness.gitReviewCommit(projectKey, { paths: selected, message })))}>Review commit</button></> : null}
        {review ? <div role="region" aria-label="Commit review"><h3>Unsigned local commit</h3><p>Branch: {review.branch}<br />Destination: local repository<br />Base: {review.head}<br />Author: {review.author}<br />Committer: {review.committer}</p><pre>{review.message}</pre>{review.files.map(file => <details key={file.path}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><FileDiff before={file.before ?? undefined} after={file.after ?? undefined} /></details>)}<button type="button" data-action="git-commit" disabled={busy || disabled || Boolean(pending)} onClick={() => void act(async () => { const id = review.ticketId; localStorage.setItem(pendingKey, id); setPending(id); setReview(undefined); const operation = await window.harness.gitCommit(projectKey, id); localStorage.removeItem(pendingKey); setPending(undefined); setResult(`Commit created: ${operation.commit}`); await refresh(); })}>Authorize local commit</button><button type="button" onClick={() => setReview(undefined)}>Back</button></div> : null}
        {pending ? <div role="status"><p>Operation awaiting confirmation: {pending}</p><button type="button" data-action="git-reconcile" disabled={busy || disabled} onClick={() => void act(async () => { const operation = await window.harness.gitReconcile(projectKey, pending); setResult(operation.status === "not-accepted" ? "The commit was not accepted. You can prepare a new review." : `Commit confirmed: ${operation.commit}`); localStorage.removeItem(pendingKey); setPending(undefined); await refresh(); })}>Check result</button></div> : null}
        <PushPanel projectKey={projectKey} disabled={disabled || busy || Boolean(pending)} /><PullRequestPanel projectKey={projectKey} disabled={disabled||busy||Boolean(pending)}/>{result ? <p role="status">{result}</p> : null}{error ? <p role="alert">{error}</p> : null}</details>;
}
