import { randomUUID, createHash } from "node:crypto";
import { mkdir, lstat, open, rename, unlink, realpath } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { z } from "zod";
import { createRedactionPolicy } from "@zhivex-ai/agents";
import { pushDestinationSchema, pushSnapshotSchema, type PushDestination, type PushSnapshot } from "./remote-delivery.js";
const oid = z.string().regex(/^[a-f0-9]{40,64}$/);
const inputSchema = z.object({ destination: pushDestinationSchema, title: z.string().trim().min(1).max(256), body: z.string().max(20000), draft: z.boolean() }).strict();
export type PullRequestInput = z.infer<typeof inputSchema>;
export const pullRequestRecordSchema = z.object({ number: z.number().int().positive(), url: z.string().url(), head: oid, base: oid, headRef: z.string(), baseRef: z.string(), title: z.string().max(256), body: z.string().max(65536), draft: z.boolean(), state: z.enum(["open", "closed"]) }).strict();
export type PullRequestRecord = z.infer<typeof pullRequestRecordSchema>;
export class PullRequestRejectedError extends Error {constructor(){super("PR_API_REJECTED");}}
export interface PullRequestTransport { inspect(destination: PushDestination): Promise<PushSnapshot>; list(destination: PushDestination): Promise<PullRequestRecord[]>; create(input: PullRequestInput): Promise<PullRequestRecord> }
export interface PullRequestReview extends PullRequestInput { ticketId: string; expiresAt: number; snapshot: PushSnapshot }
const resultSchema = z.object({ number: z.number().int().positive(), url: z.string().url(), head: oid, base: oid }).strict();
const operationSchema = z.object({ id: z.string().uuid(), destination: pushDestinationSchema, head: oid, base: oid, proposalDigest: z.string().regex(/^[a-f0-9]{64}$/), knownNumbers: z.array(z.number().int().positive()).max(1000), status: z.enum(["prepared", "completed", "needs-review", "rejected"]), result: resultSchema.optional() }).strict().refine(value => ["prepared", "rejected"].includes(value.status) ? value.result === undefined : value.result !== undefined);
export type PullRequestOperation = z.infer<typeof operationSchema>;
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const proposal = (value: { title: string; body: string; draft: boolean }) => hash({ title: value.title, body: value.body, draft: value.draft });
const repository = (destination: PushDestination) => destination.url.replace(/\.git$/, "");

/** One owner per project. Every admitted ID can issue at most one create request. */
export async function openPullRequestDelivery(directory: string, transport: PullRequestTransport, secrets: readonly string[] = []) {
    await mkdir(directory, { recursive: true, mode: 0o700 }); const stat = await lstat(directory); if (!stat.isDirectory() || stat.isSymbolicLink() || stat.uid !== process.getuid?.() || (stat.mode & 0o077) !== 0) throw new Error("PR_STATE_UNSAFE"); const root = await realpath(directory);
    const policy = createRedactionPolicy({ includeEmails: false }); const sensitive = (value: unknown): boolean => typeof value === "string" ? policy.redactText(value) !== value || /\b(?:sk|ghp|github_pat|xox[baprs])[-_][A-Za-z0-9_-]+/i.test(value) || secrets.some(secret => secret.length > 0 && value.includes(secret)) : Array.isArray(value) ? value.some(sensitive) : value !== null && typeof value === "object" ? Object.values(value).some(sensitive) : false;
    const inspect = async (input: PullRequestInput) => { if (sensitive(input)) throw new Error("PR_SECRET_DETECTED"); const snapshot = pushSnapshotSchema.parse(await transport.inspect(input.destination)); if (hash(snapshot.destination) !== hash(input.destination) || snapshot.remoteHead !== snapshot.head) throw new Error("PR_HEAD_NOT_PUBLISHED"); if (input.destination.ref === input.destination.baseRef || !snapshot.fastForward) throw new Error("PR_BASE_CONFLICT"); if (snapshot.stagedPaths.length) throw new Error("PR_STAGED_CHANGES"); if (!snapshot.commits.length || snapshot.commits.at(-1)?.id !== snapshot.head) throw new Error("PR_HISTORY_INCOMPLETE"); if (Buffer.byteLength(JSON.stringify(snapshot)) > 2 * 1024 * 1024) throw new Error("PR_PREVIEW_INCOMPLETE"); if (sensitive(snapshot)) throw new Error("PR_SECRET_DETECTED"); for (const commit of snapshot.commits) for (const file of commit.files) if (file.path.split("/").some(part => !part || part === ".." || part === "." || part === ".git" || part === ".zhivex-harness") || /[\x00-\x1f\x7f\\]/.test(file.path) || /(^|\/)(?:\.env(?:\..*)?|credentials(?:\..*)?|id_(?:rsa|ed25519)|.*\.(?:pem|p12|pfx|key))$/i.test(file.path)) throw new Error("PR_PATH_BLOCKED"); return snapshot; };
    const record = (raw: unknown, destination: PushDestination) => { const result = pullRequestRecordSchema.parse(raw); if (result.url !== `${repository(destination)}/pull/${result.number}` || result.headRef !== destination.ref.slice(11) || result.baseRef !== destination.baseRef.slice(11)) throw new Error("PR_RESPONSE_MISMATCH"); return result; };
    const list = async (destination: PushDestination) => { const raw = await transport.list(destination); if (raw.length > 1000) throw new Error("PR_HISTORY_LIMIT"); const records = raw.map(item => record(item, destination)); if (new Set(records.map(item => item.number)).size !== records.length) throw new Error("PR_HISTORY_INVALID"); return records; };
    const persist = async (operation: PullRequestOperation) => { const target = path.join(root, `${operation.id}.json`), temporary = target + `.${randomUUID()}.tmp`, file = await open(temporary, "wx", 0o600); try { await file.writeFile(JSON.stringify(operation)); await file.sync(); } finally { await file.close(); } try { await rename(temporary, target); const directory = await open(root, "r"); try { await directory.sync(); } finally { await directory.close(); } } finally { await unlink(temporary).catch(() => { }); } };
    const read = async (id: string) => { z.string().uuid().parse(id); const file = await open(path.join(root, `${id}.json`), constants.O_RDONLY | constants.O_NOFOLLOW); try { const stat = await file.stat(); if (!stat.isFile() || stat.uid !== process.getuid?.() || (stat.mode & 0o077) !== 0 || stat.size > 32768) throw new Error("PR_STATE_UNSAFE"); const operation = operationSchema.parse(JSON.parse(await file.readFile("utf8"))); if (operation.id !== id || (operation.result && operation.result.url !== `${repository(operation.destination)}/pull/${operation.result.number}`)) throw new Error("PR_OPERATION_CHANGED"); return operation; } finally { await file.close(); } };
    const finish = async (operation: PullRequestOperation, found: PullRequestRecord) => { operation.result = { number: found.number, url: found.url, head: found.head, base: found.base }; operation.status = found.head === operation.head && found.base === operation.base ? "completed" : "needs-review"; await persist(operation); return operation; };
    const reconcile = async (id: string) => { const operation = await read(id); if (operation.status !== "prepared") return operation; const candidates = (await list(operation.destination)).filter(item => !operation.knownNumbers.includes(item.number) && proposal(item) === operation.proposalDigest); if (candidates.length !== 1) throw new Error("PR_OUTCOME_UNCONFIRMED"); return finish(operation, candidates[0]!); };
    let queue = Promise.resolve(); const serial = <T>(fn: () => Promise<T>) => { const result = queue.then(fn); queue = result.then(() => { }, () => { }); return result; }; const tickets = new Map<string, { review: PullRequestReview; knownNumbers: number[] }>();
    return {
        review: (value: unknown): Promise<PullRequestReview> => serial(async () => { const input = inputSchema.parse(value), snapshot = await inspect(input), existing = await list(input.destination); if (existing.some(item => item.state === "open")) throw new Error("PR_ALREADY_EXISTS"); const ticketId = randomUUID(), review = { ...input, ticketId, expiresAt: Date.now() + 5 * 60000, snapshot }; tickets.set(ticketId, { review, knownNumbers: existing.map(item => item.number) }); while (tickets.size > 128) tickets.delete(tickets.keys().next().value!); return structuredClone(review); }),
        create: (id: string): Promise<PullRequestOperation> => serial(async () => {
            try { return await reconcile(id); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
            const ticket = tickets.get(id); if (!ticket) throw new Error("PR_REVIEW_REQUIRED"); tickets.delete(id); if (ticket.review.expiresAt <= Date.now()) throw new Error("PR_REVIEW_EXPIRED"); const input = inputSchema.parse({ destination: ticket.review.destination, title: ticket.review.title, body: ticket.review.body, draft: ticket.review.draft }); const snapshot = await inspect(input); if (hash(snapshot) !== hash(ticket.review.snapshot)) throw new Error("PR_REVIEW_CHANGED"); const existing = await list(input.destination); if (existing.some(item => item.state === "open") || hash(existing.map(item => item.number)) !== hash(ticket.knownNumbers)) throw new Error("PR_REVIEW_CHANGED");
            const operation: PullRequestOperation = { id, destination: input.destination, head: snapshot.head, base: snapshot.baseHead, proposalDigest: proposal(input), knownNumbers: ticket.knownNumbers, status: "prepared" }; await persist(operation);
            let created: PullRequestRecord | undefined; try { created = record(await transport.create(input), input.destination); } catch (error) { if (error instanceof PullRequestRejectedError) { operation.status = "rejected"; await persist(operation); return operation; } /* An ambiguous request may have succeeded; never repeat it. */ }
            if (created && proposal(created) === operation.proposalDigest && !operation.knownNumbers.includes(created.number)) return finish(operation, created);
            return reconcile(id);
        }),
        reconcile: (id: string): Promise<PullRequestOperation | { id: string; status: "not-accepted" }> => serial(async () => { try { return await reconcile(id); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { id, status: "not-accepted" }; throw error; } })
    };
}
