import {useRef,useState} from "react";
import type {PullRequestReview,PullRequestOperation} from "./pr-delivery.js";
import type {RemoteTargets} from "./github-git-transport.js";
export function PullRequestPanel({projectKey,disabled}:{projectKey:string;disabled:boolean}){
 const pendingKey=`harness.pr.pending:${projectKey}`,lastKey=`harness.pr.last:${projectKey}`;
 const [targets,setTargets]=useState<RemoteTargets>(),[remote,setRemote]=useState(""),[head,setHead]=useState(""),[base,setBase]=useState("refs/heads/main"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[draft,setDraft]=useState(true),[review,setReview]=useState<PullRequestReview>(),[pending,setPending]=useState<string|undefined>(()=>localStorage.getItem(pendingKey)??undefined),[last,setLast]=useState<string|undefined>(()=>localStorage.getItem(lastKey)??undefined),[result,setResult]=useState<PullRequestOperation>(),[busy,setBusy]=useState(false),[error,setError]=useState("");const lock=useRef(false);
 const act=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await fn();}catch(error){const code=String(error);setError(code.includes("ALREADY_EXISTS")?"Ya hay un PR abierto para estas ramas. Revisalo en GitHub.":code.includes("HEAD_NOT_PUBLISHED")?"Publicá primero el commit revisado en la rama seleccionada.":code.includes("GIT_RUNTIME_BUSY")?"Hay trabajo activo. Esperá o cancelalo antes de crear el PR.":code.includes("BASE_CONFLICT")||code.includes("REVIEW_CHANGED")?"La base o el estado revisado cambiaron. Integrá los cambios y prepará otra revisión.":code.includes("SECRET")||code.includes("PATH_BLOCKED")?"La propuesta contiene contenido sensible o archivos protegidos.":"No se confirmó la operación. Revisá conexión, permisos y autenticación de gh. Consultá cualquier operación pendiente antes de volver a crear un PR.");}finally{lock.current=false;setBusy(false);}};
 const finish=(value:PullRequestOperation|{id:string;status:"not-accepted"})=>{if(value.status==="not-accepted"){setError("No se aceptó la creación. Podés preparar otra revisión.");setResult(undefined);}else{setResult(value);if(value.result){localStorage.setItem(lastKey,value.id);setLast(value.id);}if(value.status==="rejected")setError("GitHub rechazó la creación. Corregí permisos o propuesta y prepará otra revisión.");}localStorage.removeItem(pendingKey);setPending(undefined);};
 const inactive=disabled||busy||Boolean(pending),invalidate=()=>setReview(undefined);
 return <details className="pr-panel"><summary>Crear pull request</summary><p>Revisá título, descripción, ramas y cambios publicados antes de autorizar la creación en GitHub.</p><button type="button" data-action="pr-targets" disabled={inactive} onClick={()=>void act(async()=>{const next=await window.harness.remoteTargets(projectKey);setTargets(next);setRemote("");setHead(next.branch);invalidate();})}>Consultar remotos para PR</button>
 {targets?<><label>Repositorio<select data-field="pr-remote" disabled={inactive} value={remote} onChange={event=>{setRemote(event.target.value);invalidate();}}><option value="">Elegí un remoto</option>{targets.remotes.map(item=><option key={item.remote} value={item.remote}>{item.remote} · {item.url}</option>)}</select></label><label>Ref publicada<input data-field="pr-head" value={head} disabled={inactive} onChange={event=>{setHead(event.target.value);invalidate();}} maxLength={191}/></label><label>Ref base<input data-field="pr-base" value={base} disabled={inactive} onChange={event=>{setBase(event.target.value);invalidate();}} maxLength={191}/></label><label>Título<input data-field="pr-title" value={title} disabled={inactive} onChange={event=>{setTitle(event.target.value);invalidate();}} maxLength={256}/></label><label>Descripción<textarea data-field="pr-body" value={body} disabled={inactive} onChange={event=>{setBody(event.target.value);invalidate();}} maxLength={20000}/></label><label><input type="checkbox" data-field="pr-draft" checked={draft} disabled={inactive} onChange={event=>{setDraft(event.target.checked);invalidate();}}/>Crear como borrador</label><button type="button" data-action="review-pr" disabled={inactive||!remote||!title.trim()||!head||!base} onClick={()=>void act(async()=>{const target=targets.remotes.find(item=>item.remote===remote)!;invalidate();setReview(await window.harness.reviewPr(projectKey,{destination:{...target,ref:head,baseRef:base},title,body,draft}));})}>Revisar PR</button></>:null}
 {review?<div role="region" aria-label="Revisión del PR"><h3>{review.title}</h3><pre>{review.body}</pre><p>{review.draft?"Borrador":"Listo para revisión"}<br/>Repositorio: {review.destination.url}<br/>Head: {review.destination.ref} · {review.snapshot.head}<br/>Base: {review.destination.baseRef} · {review.snapshot.baseHead}</p>{review.snapshot.commits.map(commit=><details key={commit.id}><summary>{commit.id} · {commit.message.split("\n")[0]}</summary><pre>{commit.message}</pre>{commit.files.map((file,index)=><details key={index}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><p>Comparado con {file.parent}</p><h4>Antes</h4><pre>{file.before}</pre><h4>Después</h4><pre>{file.after}</pre></details>)}</details>)}<button type="button" data-action="create-pr" disabled={inactive} onClick={()=>void act(async()=>{const id=review.ticketId;localStorage.setItem(pendingKey,id);setPending(id);invalidate();finish(await window.harness.createPr(projectKey,id));})}>Autorizar creación de PR</button><button type="button" onClick={invalidate}>Volver</button></div>:null}
 {pending?<div role="status"><p>Creación pendiente de confirmar: {pending}</p><button type="button" data-action="reconcile-pr" disabled={busy||disabled} onClick={()=>void act(async()=>finish(await window.harness.reconcilePr(projectKey,pending)))}>Consultar resultado del PR</button></div>:null}
 {last&&!result?.result?<button type="button" data-action="restore-pr" disabled={busy||disabled||Boolean(pending)} onClick={()=>void act(async()=>finish(await window.harness.reconcilePr(projectKey,last)))}>Recuperar último PR</button>:null}{result?.result?<div role="status"><p>{result.status==="needs-review"?"PR creado con cambios de head/base: requiere una nueva revisión en GitHub.":"PR confirmado."}</p><p>{result.result.url}</p>{result.status==="needs-review"?<p>Head esperado: {result.head}<br/>Head observado: {result.result.head}<br/>Base esperada: {result.base}<br/>Base observada: {result.result.base}</p>:null}<button type="button" data-action="open-pr" disabled={busy||disabled} onClick={()=>void act(()=>window.harness.openPr(projectKey,result.id))}>Abrir PR verificado</button></div>:null}
 {error?<p role="alert">{error}</p>:null}</details>;
}
