import {useRef,useState} from "react";
import type {PullRequestReview,PullRequestOperation} from "./pr-delivery.js";
import type {RemoteTargets} from "./github-git-transport.js";
export function PullRequestPanel({projectKey,disabled}:{projectKey:string;disabled:boolean}){
 const pendingKey=`harness.pr.pending:${projectKey}`,lastKey=`harness.pr.last:${projectKey}`;
 const [targets,setTargets]=useState<RemoteTargets>(),[remote,setRemote]=useState(""),[head,setHead]=useState(""),[base,setBase]=useState("refs/heads/main"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[draft,setDraft]=useState(true),[review,setReview]=useState<PullRequestReview>(),[pending,setPending]=useState<string|undefined>(()=>localStorage.getItem(pendingKey)??undefined),[last,setLast]=useState<string|undefined>(()=>localStorage.getItem(lastKey)??undefined),[result,setResult]=useState<PullRequestOperation>(),[busy,setBusy]=useState(false),[error,setError]=useState("");const lock=useRef(false);
 const act=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await fn();}catch(error){const code=String(error);setError(code.includes("ALREADY_EXISTS")?"A PR is already open for these branches. Review it on GitHub.":code.includes("HEAD_NOT_PUBLISHED")?"Push the reviewed commit to the selected branch first.":code.includes("GIT_RUNTIME_BUSY")?"Work is active. Wait or cancel it before creating the PR.":code.includes("BASE_CONFLICT")||code.includes("REVIEW_CHANGED")?"The base or reviewed state has changed. Merge the changes and prepare another review.":code.includes("SECRET")||code.includes("PATH_BLOCKED")?"The proposal contains sensitive content or protected files.":"The operation was not confirmed. Check the connection, permissions, and gh authentication. Check any pending operation before creating another PR.");}finally{lock.current=false;setBusy(false);}};
 const finish=(value:PullRequestOperation|{id:string;status:"not-accepted"})=>{if(value.status==="not-accepted"){setError("Creation was not accepted. You can prepare another review.");setResult(undefined);}else{setResult(value);if(value.result){localStorage.setItem(lastKey,value.id);setLast(value.id);}if(value.status==="rejected")setError("GitHub rejected creation. Correct the permissions or proposal and prepare another review.");}localStorage.removeItem(pendingKey);setPending(undefined);};
 const inactive=disabled||busy||Boolean(pending),invalidate=()=>setReview(undefined);
 return <details className="pr-panel"><summary>Create pull request</summary><p>Review the title, description, branches, and published changes before authorizing creation on GitHub.</p><button type="button" data-action="pr-targets" disabled={inactive} onClick={()=>void act(async()=>{const next=await window.harness.remoteTargets(projectKey);setTargets(next);setRemote("");setHead(next.branch);invalidate();})}>Check remotes for PR</button>
 {targets?<><label>Repository<select data-field="pr-remote" disabled={inactive} value={remote} onChange={event=>{setRemote(event.target.value);invalidate();}}><option value="">Choose a remote</option>{targets.remotes.map(item=><option key={item.remote} value={item.remote}>{item.remote} · {item.url}</option>)}</select></label><label>Published ref<input data-field="pr-head" value={head} disabled={inactive} onChange={event=>{setHead(event.target.value);invalidate();}} maxLength={191}/></label><label>Base ref<input data-field="pr-base" value={base} disabled={inactive} onChange={event=>{setBase(event.target.value);invalidate();}} maxLength={191}/></label><label>Title<input data-field="pr-title" value={title} disabled={inactive} onChange={event=>{setTitle(event.target.value);invalidate();}} maxLength={256}/></label><label>Description<textarea data-field="pr-body" value={body} disabled={inactive} onChange={event=>{setBody(event.target.value);invalidate();}} maxLength={20000}/></label><label><input type="checkbox" data-field="pr-draft" checked={draft} disabled={inactive} onChange={event=>{setDraft(event.target.checked);invalidate();}}/>Create as draft</label><button type="button" data-action="review-pr" disabled={inactive||!remote||!title.trim()||!head||!base} onClick={()=>void act(async()=>{const target=targets.remotes.find(item=>item.remote===remote)!;invalidate();setReview(await window.harness.reviewPr(projectKey,{destination:{...target,ref:head,baseRef:base},title,body,draft}));})}>Review PR</button></>:null}
 {review?<div role="region" aria-label="PR review"><h3>{review.title}</h3><pre>{review.body}</pre><p>{review.draft?"Draft":"Ready for review"}<br/>Repository: {review.destination.url}<br/>Head: {review.destination.ref} · {review.snapshot.head}<br/>Base: {review.destination.baseRef} · {review.snapshot.baseHead}</p>{review.snapshot.commits.map(commit=><details key={commit.id}><summary>{commit.id} · {commit.message.split("\n")[0]}</summary><pre>{commit.message}</pre>{commit.files.map((file,index)=><details key={index}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><p>Compared with {file.parent}</p><h4>Before</h4><pre>{file.before}</pre><h4>After</h4><pre>{file.after}</pre></details>)}</details>)}<button type="button" data-action="create-pr" disabled={inactive} onClick={()=>void act(async()=>{const id=review.ticketId;localStorage.setItem(pendingKey,id);setPending(id);invalidate();finish(await window.harness.createPr(projectKey,id));})}>Authorize PR creation</button><button type="button" onClick={invalidate}>Back</button></div>:null}
 {pending?<div role="status"><p>Creation awaiting confirmation: {pending}</p><button type="button" data-action="reconcile-pr" disabled={busy||disabled} onClick={()=>void act(async()=>finish(await window.harness.reconcilePr(projectKey,pending)))}>Check PR result</button></div>:null}
 {last&&!result?.result?<button type="button" data-action="restore-pr" disabled={busy||disabled||Boolean(pending)} onClick={()=>void act(async()=>finish(await window.harness.reconcilePr(projectKey,last)))}>Retrieve last PR</button>:null}{result?.result?<div role="status"><p>{result.status==="needs-review"?"PR created with head/base changes: a new review is required on GitHub.":"PR confirmed."}</p><p>{result.result.url}</p>{result.status==="needs-review"?<p>Expected head: {result.head}<br/>Observed head: {result.result.head}<br/>Expected base: {result.base}<br/>Observed base: {result.result.base}</p>:null}<button type="button" data-action="open-pr" disabled={busy||disabled} onClick={()=>void act(()=>window.harness.openPr(projectKey,result.id))}>Open verified PR</button></div>:null}
 {error?<p role="alert">{error}</p>:null}</details>;
}
