import { useRef, useState } from "react";
import type { PushReview } from "./remote-delivery.js";
import type { RemoteTargets } from "./github-git-transport.js";
export function PushPanel({ projectKey, disabled }: { projectKey: string; disabled: boolean }) {
    const pendingKey = `harness.push.pending:${projectKey}`;
    const [targets, setTargets] = useState<RemoteTargets>(), [remote, setRemote] = useState(""), [ref, setRef] = useState(""), [base, setBase] = useState("refs/heads/main"), [review, setReview] = useState<PushReview>(), [pending, setPending] = useState<string | undefined>(() => localStorage.getItem(pendingKey) ?? undefined), [busy, setBusy] = useState(false), [error, setError] = useState(""), [result, setResult] = useState(""); const lock = useRef(false);
    const act = async (fn: () => Promise<void>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await fn(); } catch (error) { const code = String(error); setError(code.includes("GIT_RUNTIME_BUSY") ? "Hay trabajo activo. Esperá o cancelalo antes de enviar." : code.includes("DIVERGED") ? "El remoto tiene cambios divergentes. Integralos localmente y volvé a revisar; no se forzará el push." : code.includes("ALREADY_CURRENT") ? "El destino ya tiene este commit." : code.includes("STAGED") ? "Hay archivos staged. Completá o revisá el commit local antes del push." : code.includes("SECRET") || code.includes("PATH_BLOCKED") ? "El historial contiene contenido sensible o archivos protegidos. Revisalo antes de enviarlo." : "No se confirmó la operación. Revisá conexión, destino y autenticación de gh en el host. Si hay una operación pendiente, consultá su resultado antes de volver a enviar."); } finally { lock.current = false; setBusy(false); } };
    const inactive = disabled || busy || Boolean(pending);
    return <details className="push-panel"><summary>Enviar commits a GitHub</summary><p>Usa GitHub por HTTPS y la sesión existente de gh en este equipo. Revisá destino e historial antes de autorizar; no se enviarán cambios sin commit.</p>
        <button type="button" data-action="remote-targets" disabled={inactive} onClick={() => void act(async () => { const next = await window.harness.remoteTargets(projectKey); setTargets(next); setRemote(""); setRef(next.branch); setReview(undefined); })}>Consultar remotos configurados</button>
        {targets ? <><p>{targets.unsupported ? `${targets.unsupported} remotos no compatibles omitidos.` : ""}</p><label>Remoto<select data-field="push-remote" value={remote} disabled={inactive} onChange={event => { setRemote(event.target.value); setReview(undefined); }}><option value="">Elegí un remoto</option>{targets.remotes.map(item => <option key={item.remote} value={item.remote}>{item.remote} · {item.url}</option>)}</select></label><label>Ref destino<input data-field="push-ref" value={ref} disabled={inactive} onChange={event => { setRef(event.target.value); setReview(undefined); }} /></label><label>Ref base existente<input data-field="push-base" value={base} disabled={inactive} onChange={event => { setBase(event.target.value); setReview(undefined); }} /></label><button type="button" data-action="review-push" disabled={inactive || !remote || !ref || !base} onClick={() => void act(async () => { const target = targets.remotes.find(item => item.remote === remote)!; setReview(undefined); setReview(await window.harness.reviewPush(projectKey, { ...target, ref, baseRef: base })); })}>Revisar push</button></> : null}
        {review ? <div role="region" aria-label="Revisión del push"><h3>Enviar commits revisados</h3><p>Rama local: {review.branch}<br />Commit: {review.head}<br />Destino: {review.destination.url}<br />Ref: {review.destination.ref}<br />Estado remoto: {review.remoteHead ?? "Rama nueva"}<br />Base: {review.destination.baseRef} · {review.baseHead}</p>{review.commits.map(commit => <details key={commit.id}><summary>{commit.id} · {commit.message.split("\n")[0]}</summary><pre>{commit.message}</pre>{commit.files.map((file, index) => <details key={index}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><p>Comparado con {file.parent}</p><h4>Antes</h4><pre>{file.before}</pre><h4>Después</h4><pre>{file.after}</pre></details>)}</details>)}<button type="button" data-action="authorize-push" disabled={inactive} onClick={() => void act(async () => { const id = review.ticketId; localStorage.setItem(pendingKey, id); setPending(id); setReview(undefined); const operation = await window.harness.push(projectKey, id); localStorage.removeItem(pendingKey); setPending(undefined); setResult(`Push confirmado: ${operation.head} → ${operation.destination.ref}`); })}>Autorizar push al destino revisado</button><button type="button" onClick={() => setReview(undefined)}>Volver</button></div> : null}
        {pending ? <div role="status"><p>Envío pendiente de confirmar: {pending}</p><button type="button" data-action="reconcile-push" disabled={disabled || busy} onClick={() => void act(async () => { const operation = await window.harness.reconcilePush(projectKey, pending); setResult(operation.status === "not-accepted" ? "No se aceptó el envío. Podés preparar una revisión nueva." : `Push confirmado: ${operation.head} → ${operation.destination.ref}`); localStorage.removeItem(pendingKey); setPending(undefined); })}>Consultar resultado del push</button></div> : null}
        {result ? <p role="status">{result}</p> : null}{error ? <p role="alert">{error}</p> : null}</details>;
}
