import { useRef, useState } from "react";
import type { PushReview } from "./remote-delivery.js";
import type { RemoteTargets } from "./github-git-transport.js";
export function PushPanel({ projectKey, disabled }: { projectKey: string; disabled: boolean }) {
    const pendingKey = `harness.push.pending:${projectKey}`;
    const [targets, setTargets] = useState<RemoteTargets>(), [remote, setRemote] = useState(""), [ref, setRef] = useState(""), [base, setBase] = useState("refs/heads/main"), [review, setReview] = useState<PushReview>(), [pending, setPending] = useState<string | undefined>(() => localStorage.getItem(pendingKey) ?? undefined), [busy, setBusy] = useState(false), [error, setError] = useState(""), [result, setResult] = useState(""); const lock = useRef(false);
    const act = async (fn: () => Promise<void>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await fn(); } catch (error) { const code = String(error); setError(code.includes("GIT_RUNTIME_BUSY") ? "Work is active. Wait or cancel it before pushing." : code.includes("DIVERGED") ? "The remote has diverging changes. Merge them locally and review again; the push will not be forced." : code.includes("ALREADY_CURRENT") ? "The destination already has this commit." : code.includes("STAGED") ? "There are staged files. Complete or review the local commit before pushing." : code.includes("SECRET") || code.includes("PATH_BLOCKED") ? "The history contains sensitive content or protected files. Review it before pushing." : "The operation was not confirmed. Check the connection, destination, and gh authentication on the host. If an operation is pending, check its result before pushing again."); } finally { lock.current = false; setBusy(false); } };
    const inactive = disabled || busy || Boolean(pending);
    return <details className="push-panel"><summary>Push commits to GitHub</summary><p>Uses GitHub over HTTPS and the existing gh session on this computer. Review the destination and history before authorizing; uncommitted changes will not be pushed.</p>
        <button type="button" data-action="remote-targets" disabled={inactive} onClick={() => void act(async () => { const next = await window.harness.remoteTargets(projectKey); setTargets(next); setRemote(""); setRef(next.branch); setReview(undefined); })}>Check configured remotes</button>
        {targets ? <><p>{targets.unsupported ? `${targets.unsupported} unsupported remotes omitted.` : ""}</p><label>Remote<select data-field="push-remote" value={remote} disabled={inactive} onChange={event => { setRemote(event.target.value); setReview(undefined); }}><option value="">Choose a remote</option>{targets.remotes.map(item => <option key={item.remote} value={item.remote}>{item.remote} · {item.url}</option>)}</select></label><label>Target ref<input data-field="push-ref" value={ref} disabled={inactive} onChange={event => { setRef(event.target.value); setReview(undefined); }} /></label><label>Existing base ref<input data-field="push-base" value={base} disabled={inactive} onChange={event => { setBase(event.target.value); setReview(undefined); }} /></label><button type="button" data-action="review-push" disabled={inactive || !remote || !ref || !base} onClick={() => void act(async () => { const target = targets.remotes.find(item => item.remote === remote)!; setReview(undefined); setReview(await window.harness.reviewPush(projectKey, { ...target, ref, baseRef: base })); })}>Review push</button></> : null}
        {review ? <div role="region" aria-label="Push review"><h3>Push reviewed commits</h3><p>Local branch: {review.branch}<br />Commit: {review.head}<br />Destination: {review.destination.url}<br />Ref: {review.destination.ref}<br />Remote state: {review.remoteHead ?? "New branch"}<br />Base: {review.destination.baseRef} · {review.baseHead}</p>{review.commits.map(commit => <details key={commit.id}><summary>{commit.id} · {commit.message.split("\n")[0]}</summary><pre>{commit.message}</pre>{commit.files.map((file, index) => <details key={index}><summary>{file.path} · {file.beforeMode} → {file.afterMode}</summary><p>Compared with {file.parent}</p><h4>Before</h4><pre>{file.before}</pre><h4>After</h4><pre>{file.after}</pre></details>)}</details>)}<button type="button" data-action="authorize-push" disabled={inactive} onClick={() => void act(async () => { const id = review.ticketId; localStorage.setItem(pendingKey, id); setPending(id); setReview(undefined); const operation = await window.harness.push(projectKey, id); localStorage.removeItem(pendingKey); setPending(undefined); setResult(`Push confirmed: ${operation.head} → ${operation.destination.ref}`); })}>Authorize push to reviewed destination</button><button type="button" onClick={() => setReview(undefined)}>Back</button></div> : null}
        {pending ? <div role="status"><p>Push awaiting confirmation: {pending}</p><button type="button" data-action="reconcile-push" disabled={disabled || busy} onClick={() => void act(async () => { const operation = await window.harness.reconcilePush(projectKey, pending); setResult(operation.status === "not-accepted" ? "The push was not accepted. You can prepare a new review." : `Push confirmed: ${operation.head} → ${operation.destination.ref}`); localStorage.removeItem(pendingKey); setPending(undefined); })}>Check push result</button></div> : null}
        {result ? <p role="status">{result}</p> : null}{error ? <p role="alert">{error}</p> : null}</details>;
}
