import { useEffect, useState } from "react";
import type { TicketedApprovalReview } from "./review-tickets.js";
export function ReviewPanel({ projectKey, sessionId, runId, revision }: { projectKey: string; sessionId: string; runId: string; revision: number }) {
    const [review, setReview] = useState<TicketedApprovalReview>(), [error, setError] = useState(""), [loading, setLoading] = useState(false);
    useEffect(() => { setReview(undefined); setError(""); }, [projectKey, sessionId, runId, revision]);
    async function decide(approve: boolean) { if (!review || loading) return; setLoading(true); setError(""); try { const result = await window.harness.resolveReview(projectKey, review.ticketId, approve); setReview(undefined); if (!result.ok) setError(["REVISION_CONFLICT", "APPROVAL_MISMATCH"].includes(result.error.code) ? "The approval expired, changed, or has already been resolved. Refresh the review." : "Could not confirm the result. Refresh the conversation before trying again."); } catch { setReview(undefined); setError("Could not retrieve the review. Refresh the conversation before trying again."); } finally { setLoading(false); } }
    async function load() { setLoading(true); setError(""); try { setReview(await window.harness.review(projectKey, sessionId, runId)); } catch { setError("Could not retrieve the review. Refresh the conversation before trying again."); } finally { setLoading(false); } }
    return <section className="review-panel" aria-label="Request review"><button type="button" className="secondary" data-action="review" disabled={loading} onClick={() => void load()}>{loading ? "Loading review…" : "Review request"}</button>
        {error ? <p role="alert">{error}</p> : null}
        {review ? <><p className="status">Run {review.runId} · revision {review.revision}</p>{review.items.map(item => <article key={item.approvalId} data-review-item={item.approvalId}>
            <h3>{item.name}</h3><p>{item.consequence}</p><p className="status">Approval {item.approvalId} · expires {new Date(item.expiresAt).toLocaleString("en-US")}</p>
            {!item.complete ? <p role="alert">Incomplete review ({item.restriction}). Do not approve from this view.</p> : null}
            {item.files.map((file, index) => <div key={index} className="review-file"><h4>{file.path}</h4><p className="status">Base: {file.expectedDigest ?? "new file"}</p>{file.operation ? <p>{file.operation === "delete" ? "Delete using recoverable quarantine" : file.operation === "create" ? "Create file" : "Update file"}</p> : null}{file.beforeMode !== undefined || file.afterMode !== undefined ? <p>Permissions: {file.beforeMode === undefined ? "missing" : `0o${file.beforeMode.toString(8)}`} → {file.afterMode === undefined ? "missing" : `0o${file.afterMode.toString(8)}`}</p> : null}<p>{file.view === "full-file" ? "Full-file diff: verified base and proposed target." : file.view === "literal-replacement" ? "Literal replacement: exact fragments; does not represent the entire file." : "Complete target content; the base is bound by its digest."}</p>{file.before !== undefined ? <pre className="removed">{file.before}</pre> : null}{file.after !== undefined ? <pre className="added">{file.after}</pre> : null}</div>)}
            {item.commands.map((cmd, index) => <pre key={index} aria-label="Reviewed command">{cmd}</pre>)}
            <details><summary>Full arguments · {item.payloadDigest}</summary><pre>{item.payload}</pre></details>
        </article>)}<p>The decision covers all displayed requests. Rejecting blocks these operations; the agent may continue with another proposal.</p><button type="button" data-action="approve-review" disabled={loading || !review.canApprove} onClick={() => void decide(true)}>Approve reviewed requests</button><button type="button" className="secondary" data-action="deny-review" disabled={loading || !review.items.length} onClick={() => void decide(false)}>Reject requests</button>{!review.canApprove ? <p>Approval requires a complete review. An outdated or incomplete base requires another review.</p> : null}</> : null}
    </section>;
}
