import { useEffect, useState } from "react";
import type { TicketedApprovalReview } from "./review-tickets.js";
export function ReviewPanel({ projectKey, sessionId, runId, revision }: { projectKey: string; sessionId: string; runId: string; revision: number }) {
    const [review, setReview] = useState<TicketedApprovalReview>(), [error, setError] = useState(""), [loading, setLoading] = useState(false);
    useEffect(() => { setReview(undefined); setError(""); }, [projectKey, sessionId, runId, revision]);
    async function decide(approve: boolean) { if (!review || loading) return; setLoading(true); setError(""); try { const result = await window.harness.resolveReview(projectKey, review.ticketId, approve); setReview(undefined); if (!result.ok) setError(["REVISION_CONFLICT", "APPROVAL_MISMATCH"].includes(result.error.code) ? "La aprobación venció, cambió o ya fue resuelta. Actualizá la revisión." : "No se pudo confirmar el resultado. Actualizá la conversación antes de reintentar."); } catch { setReview(undefined); setError("No se pudo recuperar la revisión. Actualizá la conversación antes de reintentar."); } finally { setLoading(false); } }
    async function load() { setLoading(true); setError(""); try { setReview(await window.harness.review(projectKey, sessionId, runId)); } catch { setError("No se pudo recuperar la revisión. Actualizá la conversación antes de reintentar."); } finally { setLoading(false); } }
    return <section className="review-panel" aria-label="Revisión de solicitud"><button type="button" className="secondary" data-action="review" disabled={loading} onClick={() => void load()}>{loading ? "Cargando revisión…" : "Revisar solicitud"}</button>
        {error ? <p role="alert">{error}</p> : null}
        {review ? <><p className="status">Run {review.runId} · revisión {review.revision}</p>{review.items.map(item => <article key={item.approvalId} data-review-item={item.approvalId}>
            <h3>{item.name}</h3><p>{item.consequence}</p><p className="status">Aprobación {item.approvalId} · vence {new Date(item.expiresAt).toLocaleString()}</p>
            {!item.complete ? <p role="alert">Revisión incompleta ({item.restriction}). No aprobar desde esta vista.</p> : null}
            {item.files.map((file, index) => <div key={index} className="review-file"><h4>{file.path}</h4><p className="status">Base: {file.expectedDigest ?? "archivo nuevo"}</p>{file.operation ? <p>{file.operation === "delete" ? "Eliminar mediante cuarentena recuperable" : file.operation === "create" ? "Crear archivo" : "Actualizar archivo"}</p> : null}{file.beforeMode !== undefined || file.afterMode !== undefined ? <p>Permisos: {file.beforeMode === undefined ? "ausente" : `0o${file.beforeMode.toString(8)}`} → {file.afterMode === undefined ? "ausente" : `0o${file.afterMode.toString(8)}`}</p> : null}<p>{file.view === "full-file" ? "Diff de archivo completo: base verificada y destino propuesto." : file.view === "literal-replacement" ? "Reemplazo literal: fragmentos exactos; no representa el archivo completo." : "Contenido de destino completo; la base está vinculada por su digest."}</p>{file.before !== undefined ? <pre className="removed">{file.before}</pre> : null}{file.after !== undefined ? <pre className="added">{file.after}</pre> : null}</div>)}
            {item.commands.map((cmd, index) => <pre key={index} aria-label="Comando revisado">{cmd}</pre>)}
            <details><summary>Argumentos completos · {item.payloadDigest}</summary><pre>{item.payload}</pre></details>
        </article>)}<p>La decisión abarca todas las solicitudes mostradas. Rechazar impide estas operaciones; el agente puede continuar con otra propuesta.</p><button type="button" data-action="approve-review" disabled={loading || !review.canApprove} onClick={() => void decide(true)}>Aprobar solicitudes revisadas</button><button type="button" className="secondary" data-action="deny-review" disabled={loading || !review.items.length} onClick={() => void decide(false)}>Rechazar solicitudes</button>{!review.canApprove ? <p>La aprobación requiere una revisión completa. Una base desactualizada o incompleta requiere otra revisión.</p> : null}</> : null}
    </section>;
}
