import {useEffect,useRef,useState} from "react";
import type {DesktopContext,DesktopTask,DesktopTaskRemoval} from "./bridge.js";
const labels:Record<DesktopTask["status"],string>={creating:"Creando",ready:"Disponible","needs-attention":"Requiere atención",removed:"Retirada · rama y estado conservados"};
export function TaskPanel({context,disabled,open,removed}:{context:DesktopContext;disabled:boolean;open:(id:string)=>Promise<void>;removed:(task:DesktopTask)=>Promise<void>}){
 const [tasks,setTasks]=useState<DesktopTask[]>([]),[title,setTitle]=useState(""),[branch,setBranch]=useState(""),[accepted,setAccepted]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(""),[review,setReview]=useState<DesktopTaskRemoval>();
 const action=useRef(false);
 const refresh=async()=>setTasks(await window.harness.tasks(context.project.key));
 useEffect(()=>{let alive=true;void window.harness.tasks(context.project.key).then(value=>{if(alive)setTasks(value);},()=>{if(alive)setError("No se pudieron leer las tareas. Actualizá la lista.");});return()=>{alive=false;};},[context.project.key]);
 async function create(){if(action.current||!title.trim()||!accepted)return;action.current=true;setWorking(true);setError("");try{const task=await window.harness.createTask(context.project.key,{title,...(branch.trim()?{branch:branch.trim()}:{}),initialState:"committed-head"});await refresh();setTitle("");setBranch("");setAccepted(false);await open(task.id);}catch{await refresh().catch(()=>{});setError("No se pudo crear o abrir la tarea. Revisá la lista antes de reintentar; el repositorio debe tener un commit y la rama debe ser nueva.");}finally{action.current=false;setWorking(false);}}
 async function inspect(id:string){if(action.current)return;action.current=true;setWorking(true);setError("");setReview(undefined);try{setReview(await window.harness.reviewTaskRemoval(id));}catch{setError("No se pudo verificar el worktree. Comprobá su rama y que siga disponible; no se eliminó nada.");}finally{action.current=false;setWorking(false);}}
 async function remove(){if(!review?.canRemove||action.current)return;action.current=true;setWorking(true);setError("");const ticket=review.ticketId;setReview(undefined);try{const task=await window.harness.removeTask(ticket);await refresh();await removed(task);}catch(error){setError(String(error).includes("TASK_BUSY")?"La tarea tiene trabajo activo. Cancelalo o esperá y volvé a revisar la limpieza.":"La limpieza no se completó. El estado pudo cambiar: actualizá la revisión antes de reintentar.");await refresh().catch(()=>{});}finally{action.current=false;setWorking(false);}}
 return <details className="task-panel" open={Boolean(context.task)}><summary>Tareas aisladas{context.task?` · ${context.task.title}`:""}</summary>
 {context.task?<p className="status">Rama: {context.task.branch} · Base: {context.task.baseCommit.slice(0,12)}</p>:null}
 <form onSubmit={event=>{event.preventDefault();void create();}}><h3>Nueva tarea en worktree</h3><label>Título<input data-field="task-title" value={title} onChange={event=>setTitle(event.target.value)} maxLength={120} disabled={working||disabled}/></label><label>Nueva rama<input data-field="task-branch" value={branch} onChange={event=>setBranch(event.target.value)} placeholder="feat/... (automática si se deja vacío)" maxLength={128} disabled={working||disabled}/></label><label className="task-policy"><input type="checkbox" data-field="task-policy" checked={accepted} onChange={event=>setAccepted(event.target.checked)} disabled={working||disabled}/>Partir del commit actual del repositorio origen. No copiar cambios sin commit.</label><button data-action="create-task" disabled={working||disabled||!accepted||!title.trim()}>Crear tarea</button></form>
 <button type="button" className="secondary" disabled={working||disabled} onClick={()=>void refresh().catch(()=>setError("No se pudo actualizar la lista."))}>Actualizar tareas</button>
 {tasks.map(task=><article key={task.id} data-task={task.id}><h4>{task.title}</h4><p>{labels[task.status]} · {task.branch}</p><p className="status">{task.workspace}</p><button type="button" data-action="open-task" disabled={working||disabled||task.status!=="ready"} onClick={()=>void open(task.id)}>Abrir tarea</button><button type="button" className="secondary" data-action="review-task-removal" disabled={working||disabled||task.status!=="ready"} onClick={()=>void inspect(task.id)}>Revisar limpieza</button></article>)}
 {review?<div className="task-removal" role="region" aria-label="Revisión de limpieza"><h3>Retirar {review.task.title}</h3><p>Commit de la tarea: {review.head}<br/>Commit de integración: {review.integrationCommit}</p><p>{review.unmergedCommits} commits sin integrar · {review.locked?"Worktree bloqueado":"Sin bloqueo Git"}</p>{review.changedPaths.length?<><p>Archivos pendientes, incluidos ignorados:</p><ul>{review.changedPaths.map((name,index)=><li key={index}>{name}</li>)}</ul></>:<p>No hay archivos pendientes.</p>}<p>Se retirará el checkout. La rama y el estado de las conversaciones se conservarán.</p>{!review.canRemove?<p>Integrá o preservá los cambios pendientes y quitá el bloqueo antes de limpiar.</p>:null}<button type="button" data-action="confirm-task-removal" disabled={working||disabled||!review.canRemove} onClick={()=>void remove()}>Retirar worktree revisado</button><button type="button" className="secondary" onClick={()=>setReview(undefined)}>Volver</button></div>:null}
 {error?<p role="alert">{error}</p>:null}
 </details>;
}
