import { useEffect, useRef, useState } from "react";
import type { DesktopContext, DesktopTask, DesktopTaskRemoval } from "./bridge.js";
const labels: Record<DesktopTask["status"], string> = { creating: "Creating", ready: "Available", "needs-attention": "Needs attention", removed: "Removed · branch and state preserved" };
export function TaskPanel({ context, disabled, open, removed }: { context: DesktopContext; disabled: boolean; open: (id: string) => Promise<void>; removed: (task: DesktopTask) => Promise<void> }) {
    const [tasks, setTasks] = useState<DesktopTask[]>([]), [title, setTitle] = useState(""), [branch, setBranch] = useState(""), [accepted, setAccepted] = useState(false), [working, setWorking] = useState(false), [error, setError] = useState(""), [review, setReview] = useState<DesktopTaskRemoval>();
    const action = useRef(false);
    const refresh = async () => setTasks(await window.harness.tasks(context.project.key));
    useEffect(() => { let alive = true; void window.harness.tasks(context.project.key).then(value => { if (alive) setTasks(value); }, () => { if (alive) setError("Could not read tasks. Refresh the list."); }); return () => { alive = false; }; }, [context.project.key]);
    async function create() { if (action.current || !title.trim() || !accepted) return; action.current = true; setWorking(true); setError(""); try { const task = await window.harness.createTask(context.project.key, { title, ...(branch.trim() ? { branch: branch.trim() } : {}), initialState: "committed-head" }); await refresh(); setTitle(""); setBranch(""); setAccepted(false); await open(task.id); } catch { await refresh().catch(() => { }); setError("Could not create or open the task. Check the list before trying again; the repository must have a commit and the branch must be new."); } finally { action.current = false; setWorking(false); } }
    async function inspect(id: string) { if (action.current) return; action.current = true; setWorking(true); setError(""); setReview(undefined); try { setReview(await window.harness.reviewTaskRemoval(id)); } catch { setError("Could not verify the worktree. Check its branch and availability; nothing was deleted."); } finally { action.current = false; setWorking(false); } }
    async function remove() { if (!review?.canRemove || action.current) return; action.current = true; setWorking(true); setError(""); const ticket = review.ticketId; setReview(undefined); try { const task = await window.harness.removeTask(ticket); await refresh(); await removed(task); } catch (error) { setError(String(error).includes("TASK_BUSY") ? "The task has active work. Cancel it or wait, then review cleanup again." : "Cleanup did not complete. The state may have changed: refresh the review before trying again."); await refresh().catch(() => { }); } finally { action.current = false; setWorking(false); } }
    return <details className="task-panel" open={Boolean(context.task)}><summary>Isolated tasks{context.task ? ` · ${context.task.title}` : ""}</summary>
        {context.task ? <p className="status">Branch: {context.task.branch} · Base: {context.task.baseCommit.slice(0, 12)}</p> : null}
        <form onSubmit={event => { event.preventDefault(); void create(); }}><h3>New worktree task</h3><label>Title<input data-field="task-title" value={title} onChange={event => setTitle(event.target.value)} maxLength={120} disabled={working || disabled} /></label><label>New branch<input data-field="task-branch" value={branch} onChange={event => setBranch(event.target.value)} placeholder="feat/... (automatic if left blank)" maxLength={128} disabled={working || disabled} /></label><label className="task-policy"><input type="checkbox" data-field="task-policy" checked={accepted} onChange={event => setAccepted(event.target.checked)} disabled={working || disabled} />Start from the source repository's current commit. Do not copy uncommitted changes.</label><button data-action="create-task" disabled={working || disabled || !accepted || !title.trim()}>Create task</button></form>
        <button type="button" className="secondary" disabled={working || disabled} onClick={() => void refresh().catch(() => setError("Could not refresh the list."))}>Refresh tasks</button>
        {tasks.map(task => <article key={task.id} data-task={task.id}><h4>{task.title}</h4><p>{labels[task.status]} · {task.branch}</p><p className="status">{task.workspace}</p><button type="button" data-action="open-task" disabled={working || disabled || task.status !== "ready"} onClick={() => void open(task.id)}>Open task</button><button type="button" className="secondary" data-action="review-task-removal" disabled={working || disabled || task.status !== "ready"} onClick={() => void inspect(task.id)}>Review cleanup</button></article>)}
        {review ? <div className="task-removal" role="region" aria-label="Cleanup review"><h3>Remove {review.task.title}</h3><p>Task commit: {review.head}<br />Integration commit: {review.integrationCommit}</p><p>{review.unmergedCommits} unmerged commits · {review.locked ? "Worktree locked" : "No Git lock"}</p>{review.changedPaths.length ? <><p>Pending files, including ignored files:</p><ul>{review.changedPaths.map((name, index) => <li key={index}>{name}</li>)}</ul></> : <p>No pending files.</p>}<p>The checkout will be removed. The branch and conversation state will be preserved.</p>{!review.canRemove ? <p>Merge or preserve pending changes and remove the lock before cleanup.</p> : null}<button type="button" data-action="confirm-task-removal" disabled={working || disabled || !review.canRemove} onClick={() => void remove()}>Remove reviewed worktree</button><button type="button" className="secondary" onClick={() => setReview(undefined)}>Back</button></div> : null}
        {error ? <p role="alert">{error}</p> : null}
    </details>;
}
