/** Refresh the offline console snapshot from an explicit Zhivex SDK checkout. */
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createHash } from "node:crypto";
const root = process.argv[2];
if (!root) throw new Error("Usage: bun scripts/generate-console-models.ts <sdk-checkout>");
const sdk = await Bun.file(path.join(root, "packages/sdk/package.json")).json();
const providers: Record<string, unknown> = {};
for (const provider of ["openai", "qwen", "gemini", "meta"]) {
  const source = path.join(root, `packages/sdk/src/catalog/providers/${provider}.ts`);
  const module = await import(pathToFileURL(source).href);
  const fragment = module[`${provider}CatalogFragment`];
  providers[provider] = {
    revision: fragment.revision,
    sourceSha256: createHash("sha256").update(await Bun.file(source).text()).digest("hex"),
    models: fragment.entries.filter((entry: { modelId: string; recommendedFor?: string[] }) =>
      entry.recommendedFor?.includes("tools") && entry.recommendedFor.includes("chat") &&
      !/(?:realtime|live|image|audio|tts|asr|embedding|rerank)/i.test(entry.modelId))
      .map((entry: { modelId: string }) => entry.modelId),
  };
}
await Bun.write(new URL("../src/console-model-catalog.ts", import.meta.url),
  "// Generated by scripts/generate-console-models.ts; offline suggestions, not account entitlements.\n" +
  `export const CONSOLE_MODEL_CATALOG = ${JSON.stringify({ sdkVersion: sdk.version, providers }, null, 2)} as const;\n`);
